export default {
    API_REQUEST_SEND: 'API_REQUEST_SEND',
    API_REQUEST_ERROR: 'API_REQUEST_ERROR',
    API_REQUEST_SUCCESS: 'API_REQUEST_SUCCESS',
    SET_API_REQUEST_PENDING: 'SET_API_REQUEST_PENDING',
    SET_API_REQUEST_ERROR: 'SET_API_REQUEST_ERROR',
}
